### ISSUE TITLE
SQLAlchemy 1.4 -> 2.0 Update

### ISSUE THREAD

**Issue by teald** [GeminiDRSoftware/FitsStorage#39]
## Info

This issue tracks update progress, tasks, and information w.r.t. updating SQLAlchemy. [The TODO section](##TODO) has a checklist for specific items that are completed or need to be done.

**Branch**: [`sqlalchemy_update`](https://github.com/phirstgemini/FitsStorage2/tree/sqlalchemy_update)

## TODO
- [x] Get tests running locally
- [x] [Migration Guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html) steps with `code_tests`
    - [x] Activate & Resolve [`RemovedIn20Warnings`](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings)
      - [x] (🤖) `sqlalchemy.ext.declarative.declarative_base -> sqlalchemy.orm.declarative_base` (imports, mostly)
      - [x] (🤖) `get` from session queries is unsupported: `session.query(TABLE).get(KEY) -> session.get(TABLE, KEY)`, for example
      - [x] (🔧) `sqlalchemy.orm.relation` -> `sqlalchemy.orm.relationship`
    - [x] Activate & resolve issues with [adding `future=True` to instances of `Engine`](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-engine)
      - [x] (🤖) Find all instances of `engine` instantiation.
        - It looks like there's just one in `fits_storage.db.__init__.py` that's saved. This doesn't cause any issues in the code tests with the `future=True` flag added to `create_engine` there.
        - [x] More general search by eye (`find fits* -type f -name "*.py" | xargs grep -ni -E "engine\W"`)
    - [x] Use the [`future` flag on Session](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-five-use-the-future-flag-on-session)
      - [x] (🔧) Find all instances of `Session` without `future=True`
        - [x] (🔧) This manifests in `sessionmaker(..., future=True, ...)`.
      - [x] Check for problems with `Session` instances and how they are invoked.
        - None, it seems like this is mostly enabling features on top of the pre-2.0 ones, beyond some esoteric cases not encountered in `FitsStorage2`.
    - [x] Add [`__allow_unmapped__` to explicitly typed ORM models](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-six-add-allow-unmapped-to-explicitly-typed-orm-models)
      - This had no issues.
    - [x] [Test with SQLAlchemy 2](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-seven-test-against-a-sqlalchemy-2-0-release)
    
### Misc. TODO

- [x] Add check for sqlalchemy version to automated script.

### TODO Key

(🤖) - step automated for updates to the codebase
(🔧) - could be automated
(✍️) - in progress
(💥) - major problem

## Notes

+ Both and environment variable `SQLALCHEMY_WARN_20` _and_ the `-W always::DeprecationWarning test3.py` flag _must_ be used to actually coax out the `RemovedIn20Warnings`. Unfortunately, the errors will not always correctly report unless both of these are set.
